name: Mirroring

on:
  push:
  delete:
  # create:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  to_gitlab:
    if: github.event.repository.fork == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: facarmen/repository-mirroring-action@v1.0.0
        with:
          target_repo_url: git@gitlab.com:thenewoil/website.git
          ssh_private_key: ${{ secrets.GITLAB_SSH_PRIVATE_KEY }}
